// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.installation.timestamp", "132886362836164457");
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.auto.migrated", true);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir3.308046B0AF4A39CB", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 166);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1777605764);
user_pref("browser.search.region", "US");
user_pref("datareporting.dau.cachedUsageProfileGroupID", "dea41b79-b26b-48e9-bc26-c81199fa57f7");
user_pref("datareporting.dau.cachedUsageProfileID", "09e3d1b6-479c-47f0-9455-5b6cbed419b2");
user_pref("distribution.iniFile.exists.appversion", "150.0.1");
user_pref("distribution.iniFile.exists.value", false);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20260427013024");
user_pref("extensions.lastAppVersion", "150.0.1");
user_pref("extensions.lastPlatformVersion", "150.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.uuids", "{\"data-leak-blocker@mozilla.com\":\"99f745d5-7455-483d-8dab-3a96c10ad63f\",\"formautofill@mozilla.org\":\"ae1e2358-b809-4369-9d36-70293a720166\",\"ipp-activator@mozilla.com\":\"85146681-e9d4-40a0-92d2-80782aac0998\",\"pictureinpicture@mozilla.org\":\"7e612cf1-292b-45f7-b2e4-e6756105f1c3\",\"addons-search-detection@mozilla.com\":\"fc38f5a6-b2ce-4df3-abb2-3b4cf58d02af\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"995e0979-0020-4dd9-b474-f7f400be7838\",\"default-theme@mozilla.org\":\"4afdf9b0-c238-4753-a2c5-3c85b246ac40\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("nimbus.profileId", "8fa8403e-5a0a-449b-8ff5-cf7ccb30cf51");
user_pref("pdfjs.enabledCache.state", true);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("sanity-test.device-id", "0x1636");
user_pref("sanity-test.driver-version", "27.20.11020.14001");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20260427013024");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1777605763);
user_pref("toolkit.telemetry.cachedClientID", "9a2ddf47-b3b7-4e14-9235-c64c10d8862b");
user_pref("toolkit.telemetry.cachedProfileGroupID", "203da834-10d6-42cb-aba4-65caae51b3aa");
user_pref("toolkit.telemetry.previousBuildID", "20260427013024");
